SELECT S2.CITY, LENGTH(CITY)
FROM STATION S2
WHERE LENGTH(CITY)=(SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1
;
SELECT S1.CITY, LENGTH(CITY)
FROM STATION S1
WHERE LENGTH(CITY)=(SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1
;
